# fly.toml app configuration file generated for bomgifbot on 2023-09-09T09:50:41+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bomgifbot"
primary_region = "syd"

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/go"]

[env]
  PORT = "8081"
  MASTODON_SERVER = "https://howse.social"

[http_service]
  internal_port = 8081
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
