# fly.toml app configuration file generated for bomgifbot on 2023-09-09T09:50:41+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bomgifbot"
primary_region = "syd"

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/go"]

[env]
  MASTODON_SERVER = "https://howse.social"
  GIF_URL = "http://www.bom.gov.au/radar/IDR662.gif"
